### ISSUE TITLE
Issue with auxiliary verbs

### ISSUE THREAD

**Issue by gfranzini** [lascivaroma/lasla-apn-converter#4]
Hi Thibault, I've been testing your conversion script and I come across the following error:

```
Traceback (most recent call last):
  File "./cli.py", line 294, in <module>
    cli(args.source, args.output, args.threads, args.enhanced_morph)
  File "./cli.py", line 259, in cli
    for item in pool.imap_unordered(convert_fn, iterable=input_files):
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'groups'
```
Which always happens when the script comes across auxiliary verbs which also feature a number preceding the first , e.g., (examples from three different source files):

`B01&0005_SVM                 2<institutum> erit        Pr.,4       #          `

`C00&0002_SVM                 2<ausus> es               1,5         #            `

`D76&0002_SVM                 2eram <deductus>          1           #        ` 

Any ideas what the source of the error might be?

**Comment by PonteIneptique** [comment]
Hey Greta,
The converter was designed for APN and not BPN.
I am working on it right now...

**Comment by wmshort** [comment]
Dear both, I had whipped together the following, for my purposes (and morpho tagging schema for the Latin WordNet). Maybe it can be useful in parts....

```python
from dataclasses import dataclass

@dataclass
class Morph:
    pos: str = '-'
    person: str = '-'
    degree: str = '-'
    number: str = '-'
    tense: str = '-'
    mood: str = '-'
    voice: str = '-'
    gender: str = '-'
    case: str = '-'
    group: str = '-'
    stem: str = '-'

    def __init__(self, desc: str):
        self.pos, self.person, self.number, self.tense, self.mood, self.voice, \
        self.gender, self.case, self.group, self.stem = desc
        if self.pos in ['a', 'r']:
            self.degree, self.person = self.person, '-'

    def __str__(self):
        return f"{self.pos}{self.person}{self.number}{self.tense}{self.mood}{self.voice}{self.gender}{self.case}{self.group}{self.stem}"

    def __eq__(self, other):
        results = []
        comp = str(other)
        for i, tag in enumerate(str(self)):
            if comp[i] == '-':
                results.append(True)
            else:
                results.append(comp[i] == tag)
        return all(results)

    def __add__(self, other):
        pos = self.pos if (self.pos != '-' and other.pos == '-') else other.pos
        person = self.person if (self.person != '-' and other.person == '-') else other.person
        number= self.number if (self.number != '-' and other.number == '-') else other.number
        tense = self.tense if (self.tense != '-' and other.tense == '-') else other.tense
        mood = self.mood if (self.mood != '-' and other.mood == '-') else other.mood
        voice = self.voice if (self.voice != '-' and other.voice == '-') else other.voice
        gender = self.gender if (self.gender != '-' and other.gender == '-') else other.gender
        case = self.case if (self.case != '-' and other.case == '-') else other.case
        group = self.group if (self.group != '-' and other.group == '-') else other.group
        stem = self.stem if (self.stem != '-' and other.stem == '-') else other.stem

        desc = f"{pos}{person}{number}{tense}{mood}{voice}{gender}{case}{group}{stem}"
        return Morph(desc)


def from_leipzig(gloss: str):
    if gloss:
        pos = person = number = tense = mood = voice = gender = case = group = stem = '-'

        tags = [tag.strip() for tag in gloss.upper().split('.') if tag.strip()]
        for tag in tags:
            if tag[0].isdigit():
                person = _from_leipzig[tag[0]]
                number = _from_leipzig[tag[1:]]
            if tag in ['NN', 'VB', 'ADJ', 'ADV']:
                pos = _from_leipzig[tag]
            elif tag in ['SG', 'PL']:
                number = _from_leipzig[tag]
            elif tag in ["PRS", "IMPRF", "FUT", "PRF", "PLPRF", "FUTPERF"]:
                tense = _from_leipzig[tag]
            elif tag in ["IND", "SBJV", "IMP", "PTCP", "INF", "GER", "GERV", "SUP"]:
                mood = _from_leipzig[tag]
            elif tag in ['ACT', 'PASS', 'DEP']:
                voice = _from_leipzig[tag]
            elif tag in ['M', 'F', 'N']:
                gender = _from_leipzig[tag]
            elif tag in ['NOM', 'GEN', 'DAT', 'ACC', 'ABL', 'LOC', 'VOC']:
                case = _from_leipzig[tag]

            desc = f"{pos}{person}{number}{tense}{mood}{voice}{gender}{case}{group}{stem}"
            return desc

def from_apn(gloss: str) -> str:
    if gloss:
        gender = stem = '-'
        pos, group, case, number, degree, mood, tense, voice, person, _ = \
            [_from_apn[index][tag] if tag.strip() else '-' for index, tag in enumerate(gloss)]

        if pos == 'a' and group == '2':
            group = '1'
        if pos in ['a', 'r']:
            person = degree
        if mood == 's':
            if gloss[5] == '8':
                case = 'n'
            elif gloss[5] == '9':
                case = 'a'

        desc = f"{pos}{person}{number}{tense}{mood}{voice}{gender}{case}{group}{stem}"
        return desc

_from_apn = [
    {
        # POS
        "A": "n",
        "B": "v",
        "C": "a",
        "D": "a",
        "E": "n", # PRONOUN
        "F": "-",
        "G": "-",
        "H": "-",
        "I": "-",
        "J": "-",
        "K": "-",
        "L": "-",
        "M": "r",
        "N": "r",
        "O": "r",
        "P": "r",
        "Q": "r",
        "R": "-", # PREPOSITION
        "S": "-", # CONJUNCTION
        "T": "-", # CONJUNCTION
        "U": "-", # INTERJECTION
        "#": "v",
    },
    {
      # GROUP
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5"
    },
    {
        # CASE
        "1": "n",
        "2": "v",
        "3": "a",
        "4": "g",
        "5": "d",
        "6": "b",
        "7": "l",
        "8": "-" # indeclinable
    },
    {
        # NUMBER
        "1": "s",
        "2": "p"
    },
    {
        # DEGREE
        "1": "p",
        "2": "c",
        "3": "s"
    },
    {
        # MOOD
        "1": "i",
        "2": "s",
        "3": "m",
        "4": "p",
        "5": "n",
        "6": "d",
        "7": "g",
        "8": "s",
        "9": "s",
    },
    {
        # TENSE
        "1": "p",
        "2": "i",
        "3": "f",
        "4": "r",
        "5": "l",
        "6": "t",
        "7": "r",
        "8": "l",
        "9": "f"
    },
    {
        # VOICE
        "1": "a",
        "2": "p",
        "3": "d",
        "4": "d"
    },
    {
        # PERSON
        "1": "1",
        "2": "2",
        "3": "3"
    }
]


_from_leipzig = {
        # POS
        'NN': 'n',
        'VB': 'v',
        'ADJ': 'a',
        'ADV': 'r',
        # CASE
        "NOM": "n",
        "VOC": "v",
        "ACC": "a",
        "GEN": "g",
        "DAT": "d",
        "ABL": "b",
        "LOC": "l",
        # NUMBER
        "SG": "s",
        "PL": "p",
        # DEGREE
        "POS": "p",
        "COMP": "c",
        "SUPL": "s",
        # MOOD
        "IND": "i",
        "SBJV": "s",
        "IMP": "m",
        "PTCP": "p",
        "INF": "n",
        "GER": "d",
        "GERV": "g",
        "SUP": "s",
        # TENSE
        "PRS": "p",
        "IMPRF": "i",
        "FUT": "f",
        "PRF": "r",
        "PLPRF": "l",
        "FUTPERF": "t",
        # VOICE
        "ACT": "a",
        "PASS": "p",
        "DEP": "d",
        # PERSON
        "1": "1",
        "2": "2",
        "3": "3",
        # GENDER
        'M': 'm',
        'F': 'f',
        'N': 'n'
}
```

**Comment by PonteIneptique** [comment]
I rewrote the cli to include a better matching of morphological features.

As for auxiliaries, I am currently throwing them out. It could be included but I wont on my end. You can definitely make a pull request for it. The line would be https://github.com/chartes/lasla-apn-converter/pull/5/files#diff-b15131236e6c2c6fbd87ed7939055ddeR48 :)

**Comment by gfranzini** [comment]
> Hey Greta,
> The converter was designed for APN and not BPN.
> I am working on it right now...

Right, but doesn't BPN simply add gender information to APN?

**Comment by PonteIneptique** [comment]
Maybe, which would mean the original parser was badly coded :)
The new one actually works, but it does ignore some cases.

**Comment by PonteIneptique** [comment]
FYI : I rewrote the parse_apn system into a class that is fed to threads. This allows for much more customization of behavior without cluttering the code. Feel free to improve on it :)
BTW, if you do not feel like dealing with auxiliary verbs, I am happy if you can close the issue.

@wmshort Feel free to make a pr to propose a conversion of the morph, using another argument :) I think the new class should be easier to customize.

**Comment by gfranzini** [comment]
Thanks Thibault for this! I'll close the issue and will send you a PR when we fix the auxiliary verb problem :)
